


## Media #################
###################################
  - alias: 'Chromecast ON'
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.chromecast_on
        service: turn_on
    action:
      service: homeassistant.turn_on
      entity_id: script.living_room_chromecast

 # - alias: 'TV OFF'
 #   trigger:
 #     platform: event
 #     event_type: call_service
 #     event_data:
 #       service_data:
 #         entity_id: switch.chromecast_on
 #       service: turn_off
 #   action:
 #     service: homeassistant.turn_on
 #     entity_id: script.living_room_sky
  
  - alias: 'Sky ON'
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.sky_on
        service: turn_on
    action:
      service: homeassistant.turn_on
      entity_id: script.living_room_sky

  - alias: 'Sky OFF'
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.sky_on
        service: turn_off
    action:
      service: homeassistant.turn_on
      entity_id: script.living_room_tv_off

  - alias: 'TV ON'
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.tv_on_off
        service: turn_on
    action:
      service: homeassistant.turn_on
      entity_id: script.living_room_tv_on

  - alias: 'TV OFF'
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.tv_on_off
        service: turn_off
    action:
      service: homeassistant.turn_on
      entity_id: script.living_room_tv_off

  - alias: "Chromecast playing"
    trigger:
      - platform: state
        entity_id: media_player.living_room_tv
        to: 'idle'
        from: 'off'
    action:
      service: script.turn_on
      entity_id: script.living_room_chromecast

  - alias: "Chromecast Stopped"
    trigger:
      - platform: state
        entity_id: media_player.living_room_tv
        to: 'off'
        from: 'idle'
    action:
      service: script.turn_on
      entity_id: script.living_room_sky

## Snug TV ##

  - alias: 'Snug TV ON'
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.snug_tv_on_off
        service: turn_on
    action:
      service: homeassistant.turn_on
      entity_id: script.snug_tv_on

  - alias: 'Snug TV OFF'
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.snug_tv_on_off
        service: turn_off
    action:
      service: homeassistant.turn_on
      entity_id: script.snug_tv_off

  - alias: 'Snug TV Sky ON'
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.snug_tv_sky
        service: turn_on
    action:
      service: homeassistant.turn_on
      entity_id: script.snug_tv_sky

  - alias: 'Snug TV Chromecast ON'
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.snug_tv_chromecast
        service: turn_off
    action:
      service: homeassistant.turn_on
      entity_id: script.snug_tv_chromecast

  - alias: "Snug TV Chromecast playing"
    trigger:
      - platform: state
        entity_id: media_player.snug_tv
        to: 'idle'
        from: 'off'
    action:
      service: script.turn_on
      entity_id: script.snug_tv_chromecast

  - alias: "Snug TV Chromecast Stopped"
    trigger:
      - platform: state
        entity_id: media_player.snug_tv
        to: 'off'
        from: 'idle'
    action:
      service: script.turn_on
      entity_id: script.snug_tv_sky



###################################
## Hot Water Pump #################
###################################

  - alias: 'Hot Water ON'
    trigger:
      platform: state
      entity_id: switch.hot_water
      to: 'on'
      from: 'off'
    action:
      service: homeassistant.turn_on
      entity_id: script.hot_water_on

  - alias: "Hot Water Pump: Automatically turn off"
    trigger:
      platform: state
      entity_id: switch.hot_water
      to: 'on'
      from: 'off'
    action:
      service: script.turn_on
      entity_id: script.hot_water_pump_timer

  - alias: "Hot Water Pump: reset timer"
    trigger:
      platform: state
      entity_id: switch.hot_water
      to: 'off'
      from: 'on'
    action:
      service: script.turn_off
      entity_id: script.hot_water_pump_timer



###################################
## Garage #########################
###################################
  - alias: 'Garage ON'
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.garage_door
        service: turn_on
    action:
      service: homeassistant.turn_on
      entity_id: script.garage_door_open

  - alias: 'Garage OFF'
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.garage_door
        service: turn_off
    action:
      service: homeassistant.turn_off
      entity_id: script.garage_door_close

  - alias: Close Garage at midnight
    trigger:
      platform: time
      at: '00:00:00'
    action:
      service: homeassistant.turn_off
      entity_id: script.garage_door_close


###################################
## House Gate #####################
###################################
  
  - alias: House Gate
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.house_gate
        service: turn_on
    condition:
      condition: state
      entity_id: switch.house_gate
      state: 'off'
    action:
      service: homeassistant.turn_on
      data:
        entity_id: script.gate_house_open

#  - alias: Adam Arrives Home
#    trigger:
#      platform: zone
#      entity_id: device_tracker.adam_phoneadam
#      zone: zone.home
#      event: enter
#    condition:
#      condition: state
#      entity_id: device_tracker.mr_scorpio
#      state: 'not_home'
#      for: 
#        minutes: 10
#    action:
#      service: homeassistant.turn_on
#      data:
#        entity_id: switch.house_gate


  
###################################
## Automatic lighting ###########
#################################
#  - alias: Turn on porch light after sunset
#    trigger:
#      platform: sun
#      event: sunset
#      offset: "-00:15:00"
#    action:
#      service: switch.turn_on
#      entity_id: switch.porch_lamp

  - alias: "Turn on porch as sun lowers"
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      # Can be a positive or negative number
      below: -4.0
    action:
      service: switch.turn_on
      entity_id: switch.porch_lamp

  - alias: Turn off porch light before sunrise
    trigger:
      platform: sun
      event: sunrise
      offset: "-00:30:00"
    action:
      service: switch.turn_off
      entity_id: switch.porch_lamp

  - alias: Turn on kitchen light before sunset
    trigger:
      platform: sun
      event: sunset
      offset: "-00:20:00"
    action:
      service: switch.turn_on
      entity_id: switch.kitchen_lamp
  
  - alias: Turn off kitchen light at midnight
    trigger:
      platform: time
      at: '00:00:00'
    action:
      service: switch.turn_off
      entity_id: switch.kitchen_lamp

  - alias: Turn on snug light after sunset
    trigger:
      platform: sun
      event: sunset
      offset: "+00:20:00"
    action:
      service: switch.turn_on
      entity_id: switch.snug_lamp
  
  - alias: Turn off snug light at midnight
    trigger:
      platform: time
      at: '00:00:00'
    action:
      service: switch.turn_off
      entity_id: switch.snug_lamp

  - alias: Turn on Living Room light after sunset
    trigger:
      platform: sun
      event: sunset
      offset: "+00:40:00"
    action:
      service: switch.turn_on
      entity_id: switch.living_room_lamp
  
  - alias: Turn off Living Room light at midnight
    trigger:
      platform: time
      at: '00:27:00'
    action:
      service: switch.turn_off
      entity_id: switch.living_room_lamp

  - alias: 'All Lamps Off'
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.all_lamps_on_off
        service: turn_off
    action:
      service: homeassistant.turn_off
      entity_id: group.lights2

  - alias: 'All Lamps On'
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.all_lamps_on_off
        service: turn_on
    action:
      service: homeassistant.turn_on
      entity_id: group.lights2

  - alias: Turn on back outside lights after sunset
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      # Can be a positive or negative number
      below: -4.0
    condition:
      condition: state
      entity_id: switch.outside_lights_back
      state: 'off'
    action:
      service: switch.turn_on
      entity_id: switch.outside_lights_back

  - alias: Turn off back outside lights at midnight
    trigger:
      platform: time
      at: '23:30:00'
    condition:
      condition: state
      entity_id: switch.outside_lights_back
      state: 'on'
    action:
      service: switch.turn_off
      entity_id: switch.outside_lights_back

  - alias: Turn on front outside lights after sunset
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      # Can be a positive or negative number
      below: -4.0
    condition:
      condition: state
      entity_id: switch.outside_lights_front
      state: 'off'
    action:
      service: switch.turn_on
      entity_id: switch.outside_lights_front

  - alias: Turn off front outside lights at midnight
    trigger:
      platform: time
      at: '23:00:00'
    condition:
      condition: state
      entity_id: switch.outside_lights_back
      state: 'on'
    action:
      service: switch.turn_off
      entity_id: switch.outside_lights_front


###################################
## Chrtimas Lights ########
#################################
#
#  - alias: Turn on Christmas tree when getting dark
#    trigger:
#      platform: sun
#      event: sunset
#      offset: "-02:00:00"
#    action:
#      service: switch.turn_on
#      entity_id: switch.christmas_tree
#
#  - alias: Turn off Christmas tree at 1am
#    trigger:
#      platform: time
#      at: '01:00:00'
#    action:
#      service: switch.turn_off
#      entity_id: switch.christmas_tree
#
#  - alias: Turn on Christmas Lights kitchen when getting dark
#    trigger:
#      platform: sun
#      event: sunset
#      offset: "-02:00:00"
#    action:
#      service: switch.turn_on
#      entity_id: switch.christmas_lights_kitchen
#
#  - alias: Turn off Christmas lights kitchen at 1am
#    trigger:
#      platform: time
#      at: '01:00:00'
#    action:
#      service: switch.turn_off
#      entity_id: switch.christmas_lights_kitchen
#
#  - alias: Turn on Christmas lights porch when getting dark
#    trigger:
#      platform: sun
#      event: sunset
#      offset: "-02:00:00"
#    action:
#      service: switch.turn_on
#      entity_id: switch.christmas_lights_porch
#
#  - alias: Turn off Christmas lights portch at 1am
#    trigger:
#      platform: time
#      at: '01:00:00'
#    action:
#      service: switch.turn_off
#      entity_id: switch.christmas_lights_porch



################################# 
## Bedroom ######################
#################################
#  - alias: Turn on electric blanket at 9pm
#    trigger:
#      platform: time
#      at: '20:35:00'
#    condition:
#      condition: state
#      entity_id: device_tracker.bcfb
#      state: 'home'
#    action:
#      service: switch.turn_on
#      entity_id: switch.electric_blanket_brenda
#
#  - alias: Turn off electric blanket at midnight
#    trigger:
#      platform: time
#      at: '00:00:05'
#    action:
#      service: switch.turn_off
#      entity_id: switch.electric_blanket_brenda
#
#  - alias: Turn on electric blanket when arriving home
#    trigger:
#      platform: state
#      entity_id: device_tracker.bcfb
#      to: 'home'
#    condition:
#      condition: time
#      after: '20:35:00'
#      before: '00:00:00'
#    action:
#      service: switch.turn_on
#      entity_id: switch.electric_blanket_brenda





#################################
## MQTT Car Presence ############
#################################

  - alias: OpenGateAdam_ComingHome
    trigger:
      platform: state
      entity_id: switch.adam_car
      to: 'on'
      from: 'off'
    condition:
    - condition: state
      entity_id: binary_sensor.carpresence1
      state: 'off'
      for: 
        minutes: 10 
    action:
    - service: homeassistant.turn_on
      entity_id: script.gate_open

# car sensor is connected and the garage door is closed
  - alias: CarPresence_ON
    trigger:
      platform: state
      entity_id: binary_sensor.carpresence1
      to: 'on'
      from: 'off'
    condition:
    - condition: state
      entity_id: switch.adam_car
      state: 'off'
    action:
    - service: homeassistant.turn_on
      entity_id: script.gate_open


  - alias: Adam Car Off
    trigger:
      platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id: switch.adam_car
        service: turn_on
    action:
      service: switch.turn_off
      entity_id: switch.adam_car
