title: My Awesome Home
# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
    # View tab title.
  - title: Home
    icon: mdi:home
    # Optional unique id for direct access /lovelace/${id}
    id: home
    # Optional background (overwrites the global background).
    #background: radial-gradient(crimson, skyblue)
    background: center / cover no-repeat url("/local/background.jpg") fixed
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
        # The filter card will filter entities for their state
      - type: entity-filter
        entities:
          - device_tracker.mr_scorpio
          - device_tracker.bcfb
          - device_tracker.paulinesiphone
          - device_tracker.pbeirnesiphone
          - device_tracker.samsunggalaxys7edge
        state_filter:
          - 'home'
        card: 
          type: glance
          title: Who's home?

      - type: vertical-stack
        cards:
        - type: glance
          title: Lights
          show_name: true
          show_state: false
          entities:
            - entity: group.lights2
              name: All Lights
              tap_action: 
                action: toggle
            - entity: switch.kitchen_lamp
              tap_action: 
                action: toggle
            - entity: switch.living_room_lamp
              tap_action: 
                action: toggle
            - entity: switch.porch_lamp
              tap_action: 
                action: toggle
            - entity: switch.snug_lamp
              tap_action: 
                action: toggle

        - type: glance
          title: Water
          show_state: false
          entities:
            - entity: switch.hot_water
#              tap_action: 
#                action: toggle

        - type: glance
          title: Outside
          show_name: true
          show_state: false
          entities:
            - entity: switch.outside_lights_back
              tap_action: 
                action: toggle
            - entity: switch.outside_lights_front
              tap_action: 
                action: toggle
            - entity: switch.house_gate
              tap_action: 
                action: toggle
            - entity: switch.garage_door
              tap_action: 
                action: toggle


#            - entity: switch.electric_blanket_brenda
#              tap_action: toggle
#            - entity: switch.roborock
#              tap_Action: toggle

#### CHRISTMAS #####
#      - type: glance
#        title: Christmas
#        show_state: false
#        entities: 
#          - entity: switch.christmas_tree
#            tap_action: toggle
#          - entity: switch.christmas_lights_kitchen
#            tap_action: toggle
#          - entity: switch.christmas_lights_porch
#            tap_action: toggle
   
#### WEATHER #####   
#      - type: weather-forecast
#        entity: weather.yweather
#        name: Weather

#      - type: iframe
#        url: https://www.powr.io/plugins/weather/view?unique_label=7690c273_1533136555&external_type=iframe
#        aspect_ratio: 150%
       
    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Home View
    cards:
#      - type: custom:plan-coordinates
      - type: picture-elements
        image: /local/home.jpg
        elements: 
          - type: state-icon
            tap_action: toggle
            entity: switch.hot_water
            style: 
              top: 38%
              left: 90%
              #width: 5%
              #height: 5%
              background: RGBA(255,255,255,0.7)
              border: 1px solid black
              border-radius: 25%
              state_filter:
                "on": brightness(110%) saturate(1.2)
          - type: state-icon
            tap_action: toggle
            entity: switch.kitchen_lamp
            style:
              top: 25%
              left: 90%
              background: RGBA(255,255,255,0.7)
              border: 1px solid black
              border-radius: 25%
          - type: state-icon
            tap_action: toggle
            entity: switch.snug_lamp
            style:
              top: 63%
              left: 90%
              background: RGBA(255,255,255,0.7)
              border: 1px solid black
              border-radius: 25%
          - type: state-icon
            tap_action: toggle
            entity: switch.living_room_lamp
            style:
              top: 72%
              left: 84%
              background: RGBA(255,255,255,0.7)
              border: 1px solid black
              border-radius: 25%
          - type: state-icon
            tap_action: toggle
            entity: switch.porch_lamp
            style:
              top: 86%
              left: 72%
              background: RGBA(255,255,255,0.7)
              border: 1px solid black
              border-radius: 25%
#          - type: state-icon
#            tap_action: toggle
#            entity: switch.electric_blanket_brenda
#            style:
#              top: 75%
#              left: 32%
#              background : RGBA(255,255,255,0.7)
#              border: 1px solid black
#              border-radius: 25%
          - type: state-icon
            tap_action: toggle
            entity: switch.garage_door
            style:
              top: 83%
              left: 12%
              background: RGBA(255,255,255,0.7)
              border: 1px solid black
              border-radius: 25%
          - type: state-icon
            tap_action: toggle
            entity: switch.outside_lights_back
            style:
              top: 33%
              left: 62%
              background: RGBA(255,255,255,0.7)
              border: 1px solid black
              border-radius: 25%

  - icon: mdi:cctv
    title: Cameras
    cards:
      - type: picture-entity
        entity:  camera.generic_camera
        image: http://192.168.1.50/cgi-bin/snapshot.cgi?chn=3&u=admin&p=&q=0&d=1&rand=0.746812061041008 
    
